import { useGLTF, useTexture } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { RepeatWrapping } from "three";
import { color } from "three/examples/jsm/nodes/Nodes.js";

export default function World(props) {
  const { nodes, materials } = useGLTF("/assets/models/world/Bosquev7.glb");

  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <RigidBody type="fixed" colliders="trimesh">
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Isla001.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Isla2.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Isla3.geometry}
            material={materials["Material.001"]}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fuego.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barco.geometry}
            material={materials["Texture-base.014"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tronco010.geometry}
            material={materials.Brown}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PilaRocas.geometry}
            material={materials.RocasAgua}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.arco.geometry}
            material={materials.RocasAgua}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Landscape.geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Landscape_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Landscape_2.geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Landscape_3.geometry}
            material={materials.tierra}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Casa_1.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Casa_2.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.Brown3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.Gray2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_2.geometry}
            material={materials.Yellow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_2.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials["Gray 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_1.geometry}
            material={materials["Gray 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_2.geometry}
            material={materials["Red 4"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_3.geometry}
            material={materials["Light Brown"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_4.geometry}
            material={materials["Dark Brown"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane148.geometry}
            material={materials["Entrace.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane148_1.geometry}
            material={materials["Stone.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.oro}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials.estrella}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Antorchas1.geometry}
            material={materials.Antorcha}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Antorchas2.geometry}
            material={materials["Antorcha.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_1_texrture_atlas_0.geometry}
            material={materials.Brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_1_texrture_atlas_0_1.geometry}
            material={materials.Brown3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Firewood_3_texrture_atlas_0.geometry}
            material={materials.Brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Firewood_3_texrture_atlas_0_1.geometry}
            material={materials.Brown3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_1001_texrture_atlas_0.geometry}
            material={materials.Brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_1001_texrture_atlas_0_1.geometry}
            material={materials.Brown3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere002.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere002_1.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere002_2.geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere002_3.geometry}
            material={materials.tierra}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LagoCollider.geometry}
            material={materials.Material}
          />
        </RigidBody>
      </group>

      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.LotoC023.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC022.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC020.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC019.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC018.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC014.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC012.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC011.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC010.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC009.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC008.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC007.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC006.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC005.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC004.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC003.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC002.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC001.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoC.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA036.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA035.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA034.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA032.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA031.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA029.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA028.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA027.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA026.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA025.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA021.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA018.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA017.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA016.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA015.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA014.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA012.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA011.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA010.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA009.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA008.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA007.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA006.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA005.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA004.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA003.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA002.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA001.geometry} material={materials.Loto} />
        <mesh geometry={nodes.LotoA.geometry} material={materials.Loto} />
      </RigidBody>

      <RigidBody type="fixed" colliders="hull">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BarcoDañado.geometry}
          material={materials.Barco}
        />
        <mesh
          geometry={nodes.Cylinder067.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder067_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder067_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder066.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder066_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder066_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder065.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder065_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder065_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder064.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder064_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder064_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder063.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder063_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder063_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder062.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder062_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder062_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder061.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder061_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder061_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder060.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder060_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder060_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder059.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder059_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder059_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder058.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder058_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder058_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder057.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder057_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder057_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder056.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder056_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder056_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder055.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder055_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder055_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder054.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder054_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder054_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder053.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder053_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder053_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder052.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder052_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder052_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Cylinder051.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder051_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder051_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane147.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane147_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder050.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder050_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder050_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane146.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane146_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder049.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder049_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder049_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane145.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane145_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane144.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane144_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder048.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder048_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder048_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane143.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane143_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder046.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder046_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder046_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane142.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane142_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder045.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder045_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder045_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane141.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane141_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder044.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder044_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder044_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane140.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane140_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane139.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane139_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder043.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder043_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder043_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane138.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane138_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder042.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder042_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder042_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane137.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane137_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane136.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane136_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder041.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder041_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder041_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane135.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane135_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane134.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane134_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane133.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane133_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder039.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder039_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder039_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane132.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane132_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder038.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder038_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder038_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane131.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane131_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder036.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder036_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder036_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane130.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane130_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder035.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder035_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder035_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane129.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane129_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder034.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder034_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder034_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane128.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane128_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder033.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder033_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder033_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane075.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane075_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder032.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder032_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder032_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane127.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane127_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane126.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane126_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane125.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane125_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder031.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder031_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder031_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane124.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane124_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane123.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane123_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder030.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder030_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder030_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane122.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane122_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane121.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane121_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane120.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane120_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder029.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder029_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder029_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane119.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane119_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder028.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder028_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder028_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane118.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane118_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane117.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane117_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane116.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane116_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder027.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder027_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder027_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane115.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane115_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder026.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder026_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder026_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane114.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane114_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder025.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder025_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder025_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane113.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane113_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder024.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder024_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder024_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane112.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane112_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder022.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder022_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder022_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane111.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane111_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane110.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane110_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Cylinder023.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder023_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder023_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane109.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane109_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane108.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane108_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane107.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane107_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane106.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane106_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane105.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane105_1.geometry}
          material={materials["Green 2.001"]}
        />
        <mesh
          geometry={nodes.Plane104.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane104_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane103.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane103_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane102.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane102_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane101.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane101_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder021.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder021_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder021_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane100.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane100_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane099.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane099_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane098.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane098_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder020.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder020_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder020_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane097.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane097_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder019.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder019_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder019_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane096.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane096_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane095.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane095_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane094.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane094_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane093.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane093_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder018.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder018_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder018_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane092.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane092_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane091.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane091_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane090.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane090_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder017.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder017_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder017_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane089.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane089_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane088.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane088_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane087.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane087_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder016.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder016_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder016_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane086.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane086_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane085.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane085_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane084.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane084_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder015.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder015_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane083.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane083_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane082.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane082_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane081.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane081_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane080.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane080_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane079.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane079_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Plane078.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane078_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder014.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder014_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder014_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane077.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane077_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder013.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.VerdeO}
        />
        <mesh
          geometry={nodes.Plane076.geometry}
          material={materials.ArbolOsc}
        />
        <mesh
          geometry={nodes.Plane076_1.geometry}
          material={materials.CafeArbol}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.VerdeC}
        />
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.CafeClaro}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.VerdeO}
        />
      </RigidBody>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lago.geometry}
        material={materials.Blue}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Algas.geometry}
        material={materials.Algaimg}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plantas.geometry}
        material={materials.plantas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Algas2.geometry}
        material={materials.Algas2}
      />
    </RigidBody>
  );
}

useGLTF.preload("/assets/models/world/Bosquev6.glb");
